name: Build Android APK

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build with Official Buildozer Docker
      uses: docker://kivy/buildozer:latest
      with:
        args: android debug
      env:
        BUILDOZER_ALLOW_ROOT: "1"
        BUILDOZER_ALLOW_ROOT_QUIET: "1"

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: bin/*.apk
        
